name: Design Tokens Workflow

on:
  push:
    branches:
      - design-tokens
    paths:
      - '.style-dictionary/**/tokens.json'

jobs:
  process-design-tokens:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install

    - name: Transform tokens
      run: ./node_modules/.bin/token-transformer .style-dictionary/tokens/tokens.json .style-dictionary/tokens/converted-semantic-tokens.json semantic primitive

    - name: Build style dictionary
      run: yarn build-style-dictionary
